change
stavlirt/homework pull request #14
Opened 2023-07-18 15:37 UTC by stavlirt

дз21

2023-07-31 21:38 UTC, marianaD4 requested changes

2023-07-31 21:38 UTC, marianaD4 commented on дз22/main.css
> +100% {background-color: violet;}
має бути 5 кроків, через кожні 20%

2023-07-31 21:38 UTC, marianaD4 commented on дз22/main.css
> +   animation-timing-function: 20%;
Для `animation-timing-function` значення у відсотках не задаємо
https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timing-function

2023-07-31 21:38 UTC, marianaD4 commented on дз22/main.css
> +animation-timing-function: 20%;
Потрібна лінійна часова функція

2023-07-31 21:38 UTC, marianaD4 commented on дз22/main.css
> +    }
уважно із кроками. В умові вказано 20% та 80%.
Збільшення у 1,5 рази від 100px буде 150px або краще transform: scale(1.5)

2023-08-06 22:23 UTC, stavlirt commented on дз22/main.css
> +100% {background-color: violet;}
исправила

2023-08-06 22:25 UTC, stavlirt commented on дз22/main.css
> +    }
исправила

2023-08-06 22:25 UTC, stavlirt commented on дз22/main.css
> +animation-timing-function: 20%;
исправила

2023-08-06 22:29 UTC, merged